# Generated by Django 5.1.4 on 2024-12-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_employee', '0002_alter_employee_mob_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
