# Generated by Django 5.1.4 on 2024-12-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_employee', '0003_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
