# Generated by Django 5.1.4 on 2024-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_employee', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_password',
            field=models.CharField(default='priya', max_length=50),
            preserve_default=False,
        ),
    ]
